# Generated by Django 2.2.5 on 2019-09-19 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VQAImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Upload your image')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='Input your question')),
                ('answer', models.CharField(max_length=50, verbose_name='Answer of the question')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.VQAImage', verbose_name='image')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 's',
            },
        ),
    ]
