# Generated by Django 2.2.5 on 2019-09-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vqaimage',
            name='user',
        ),
    ]
